# Generated by Django 2.0.2 on 2019-05-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'mascota', 'verbose_name_plural': 'mascotas'},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'verbose_name': 'vacuna', 'verbose_name_plural': 'vacunas'},
        ),
    ]
